image: python:latest

on:
  workflow_dispatch:

stages:
  - test

before_script:
  - python --version
  - pip install virtualenv
  - virtualenv -p python venv
  - source venv/bin/activate
  - pip install -r requirements.txt
  - pip install -e .

flake8:
  stage: test
  script:
    - flake8

mypy:
  stage: test
  script:
    - mypy src test

pytest:
  stage: test
  script:
    - pytest
  artifacts:
    paths:
      - htmlcov

pylint:
  stage: test
  script:
    - pylint src test

