# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python --version
        python -m pip install --upgrade pip
        pip install virtualenv
        virtualenv -p python venv
        source venv/bin/activate
        pip install -e .
    - name: Lint with flake8
      uses: py-actions/flake8@v2

    - name: Lint with pylint
      uses: fylein/python-pylint-github-action@v1
      with:
        args: pylint --rcfile=.pylintrc src test

    - name: Static Code check with mypy
      uses: jpetrucciani/mypy-check@master

    - name: Test with pytest
      uses: cclauss/GitHub-Action-for-pytest@0.5.0

    - name: 'Upload Artifact'
      uses: actions/upload-artifact@v3
      with:
        name: coverage report
        path: htmlcov
        retention-days: 1